sp_report/SPReport_mvc/MAF.WEB/Controllers/ReportController.cs
using MAF.BAL;
using MAF.BAL.Model;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MAF.WEB.Controllers
{

     [Authorize]
    public class ReportController : Controller
    {
        [HttpGet]
         public ActionResult Test()
        {
            try
            {
                // Create date objects 
                TimeSpan tsFrom = new TimeSpan(-1, 23, 59, 59);
                TimeSpan tsTo = new TimeSpan(0, 23, 59, 59);
                UserLoginReportViewModel paramModel = new UserLoginReportViewModel()
                {
                    FromDate = DateTime.Now.Date + tsFrom,
                    ToDate = DateTime.Now.Date + tsTo
                };


                ViewBag.ShowIframe = false;
                Session["LoadReport"] = false;
                return View(paramModel);
            }
            catch (Exception ex)
            {
                Logger.WriteErrorLog("Error in Get ActionResult Test", ex);
            }
            return RedirectToAction("Login", "Account");// We will return it logout page if any error occur
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Test(UserLoginReportViewModel reportParams)
        {
            try
            {
                if (ModelState.IsValid)
                {
                   
                    Session["ReportName"] = MAF.BAL.ResourceFile.Common.test;
                    Session["AccountNumber"] = reportParams.AccountNumber;
                    Session["FromDate"] = reportParams.FromDate.ToString(CultureInfo.CurrentCulture);
                    Session["ToDate"] = reportParams.ToDate.ToString(CultureInfo.CurrentCulture);

                    //Show iframe to load report
                    ViewBag.ShowIframe = true;
                    Session["LoadReport"] = true;
                }
                else
                {
                    //Hide iframe to load report
                    ViewBag.ShowIframe = false;
                    Session["LoadReport"] = false;
                }
                return View(reportParams);
            }
            catch (Exception ex)
            {
                Logger.WriteErrorLog("Error in Post ActionResult Test Report", ex);
            }
            return RedirectToAction("Test", "Account"); // We will return it logout page if any error occur
        }

        [HttpGet]
        public ActionResult NotificationsByTextOptInOptOut()
        {
            try
            {
                // Create date objects 
                TimeSpan tsFrom = new TimeSpan(-1, 23, 59, 59);
                TimeSpan tsTo = new TimeSpan(0, 23, 59, 59);
                NotificationsByTextOptInOptOutModel paramModel = new NotificationsByTextOptInOptOutModel()
                {
                    FromDate = DateTime.Now.Date + tsFrom,
                    ToDate = DateTime.Now.Date + tsTo
                };


                ViewBag.ShowIframe = false;
                Session["LoadReport"] = false;
                return View(paramModel);
            }
            catch (Exception ex)
            {
                Logger.WriteErrorLog("Error in Get ActionResult NotificationsByTextOptInOptOutModel", ex);
            }
            return RedirectToAction("Login", "Account"); // We will return it logout page if any error occur
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult NotificationsByTextOptInOptOut(NotificationsByTextOptInOptOutModel reportParams)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    Session["ReportName"] = MAF.BAL.ResourceFile.Common.GetNotificationsByTextOptInOptOutReport;
                    Session["AccountNumber"] = reportParams.AccountNumber;
                    Session["FromDate"] = reportParams.FromDate.ToString(CultureInfo.CurrentCulture);
                    Session["ToDate"] = reportParams.ToDate.ToString(CultureInfo.CurrentCulture);
                    Session["Type"] = reportParams.Type;
                    //Show iframe to load report
                    ViewBag.ShowIframe = true;
                    Session["LoadReport"] = true;
                }
                else
                {
                    //Hide iframe to load report
                    ViewBag.ShowIframe = false;
                    Session["LoadReport"] = false;
                }
                return View(reportParams);
            }
            catch (Exception ex)
            {
                Logger.WriteErrorLog("Error in Post ActionResult Test Report", ex);
            }
            return RedirectToAction("Test", "Account"); // We will return it logout page if any error occur
        }

        [HttpGet]
        public ActionResult AllNotificationsByText()
        {
            try
            {
                ViewBag.ShowIframe = false;
                Session["LoadReport"] = false;
                return View();
            }
            catch (Exception ex)
            {
                Logger.WriteErrorLog("Error in Get ActionResult AllNotificationsByText", ex);
            }
            return RedirectToAction("Login", "Account"); // We will return it logout page if any error occur
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult AllNotificationsByText(AllNotificationsByModel reportParams)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    Session["ReportName"] = MAF.BAL.ResourceFile.Common.AllNotificationsByTextReport;
                    Session["AccountNumber"] = reportParams.AccountNumber;
                    //Show iframe to load report
                    ViewBag.ShowIframe = true;
                    Session["LoadReport"] = true;
                }
                else
                {
                    //Hide iframe to load report
                    ViewBag.ShowIframe = false;
                    Session["LoadReport"] = false;
                }
                return View(reportParams);
            }
            catch (Exception ex)
            {
                Logger.WriteErrorLog("Error in Post ActionResult Test Report", ex);
            }
            return RedirectToAction("Test", "Account"); // We will return it logout page if any error occur
        }
	
     
     
     }
}

sp_report/SPReport_mvc/MAF.WEB/Views/Report/AllNotificationsByText.cshtml
@model MAF.BAL.Model.AllNotificationsByModel
@{
    ViewBag.Title = "AllNotificationsByTextReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    #report-frame {
        height: 331px;
    }

    @@media only screen and (min-width: 1680px) {
        #report-frame {
            height: 650px;
        }
    }

    @@media only screen and (min-width: 1920px) {
        #report-frame {
            height: 680px;
        }
    }
</style>
<link href="~/Content/plugin/datepicker/css/jquery-datetimepicker.css" rel="stylesheet" />
<div class="container-fluid dash_link pad_lt0 pad_rt0">
    <div class="row mar_btm10">
        <div class="col-lg-12 mobile_marbtm10">
            <h5 class="mar_top0">
                <b>All Payment Report</b>
            </h5>
            @using (Html.BeginForm("AllNotificationsByText", "Report", FormMethod.Post, new { id = "filterform" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="filter_wrapper">
                    <div class="row">
                   
                       
                        
                        <div class="col-sm-3">
                            <div class="form-group mar_btm10">
                                <label>Account Number</label>
                                @Html.TextBoxFor(m => m.AccountNumber, new { @class = "form-control", id = "AccountNumber", placeholder = "Enter Account Number", maxlength = 7 })
                                @Html.ValidationMessageFor(m => m.AccountNumber)
                            </div>
                        </div>
                       
                        <div class="clearfix"></div>
                        
                        <div class="col-sm-4">

                        </div>
                        <div class="col-sm-2">
                            <div class="form-group text-right mar_btm0 mar_top25">
                                <input type="submit" class="btn btn-default view-report" value="View Report" />
                            </div>
                        </div>
                    </div>
                </div>

            }
            @if (ViewBag.ShowIframe)
            {
                <iframe src='@Url.Content("~/Reports/AllNotificationsByText.aspx")' width="100%" style="border: none;" id="report-frame"></iframe>
            }
        </div>
    </div>

</div>

@section scripts
{
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryval")
    <script src="~/Content/plugin/select2/js/select2.min.js"></script>
    <script src="~/Content/plugin/datepicker/js/jquery-datetimepicker.js"></script>
    <script>
        $.validator.defaults.focusInvalid = false;
        $.validator.unobtrusive.adapters.add(
        'isdateafter', ['propertytested', 'allowequaldates'], function (options) {
            options.rules['isdateafter'] = options.params;
            options.messages['isdateafter'] = options.message;
        });
        $.validator.addMethod("isdateafter", function (value, element, params) {
            var startdatevalue = $('input[name="' + params.propertytested + '"]').val();
            if (!value || !startdatevalue) return true;
            return (params.allowequaldates) ? Date.parse(startdatevalue) <= Date.parse(value) : Date.parse(startdatevalue) < Date.parse(value);
        }, '');
        $(function () {
            $('#FromDate').datetimepicker({
                //defaultTime: '00:01 AM',
                maxDate: new Date,
                formatTime: 'g:i A',
                format: 'm/d/Y h:i A',
                step: 5
            });
            $('#ToDate').datetimepicker({
                //defaultTime: '11:59 PM',
                maxDate: new Date,
                formatTime: 'g:i A',
                format: 'm/d/Y h:i A',
                step: 5
            });
            $('#ddlStatus').select2();
        });
    </script>
}

sp_report/SPReport_mvc/MAF.WEB/Views/Report/NotificationsByTextOptInOptOut.cshtml
@model MAF.BAL.Model.NotificationsByTextOptInOptOutModel
@{
    ViewBag.Title = "NotificationsByTextOptInOptOut";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    #report-frame {
        height: 331px;
    }

    @@media only screen and (min-width: 1680px) {
        #report-frame {
            height: 650px;
        }
    }

    @@media only screen and (min-width: 1920px) {
        #report-frame {
            height: 6800px;
        }
    }
</style>
<link href="~/Content/plugin/datepicker/css/jquery-datetimepicker.css" rel="stylesheet" />
<div class="container-fluid dash_link pad_lt0 pad_rt0">
    <div class="row mar_btm10">
        <div class="col-lg-12 mobile_marbtm10">
            <h5 class="mar_top0">
                <b>All Payment Report</b>
            </h5>
            @using (Html.BeginForm("NotificationsByTextOptInOptOut", "Report", FormMethod.Post, new { id = "filterform" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="filter_wrapper">
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group mar_btm10">
                                <label>From Date</label>
                                <div class="inner-addon right-addon">
                                    <i class="fa fa-calendar"></i>
                                    @Html.TextBoxFor(m => m.FromDate, "{0:MM/dd/yyyy hh:mm tt}", new { id = "FromDate", @class = "form-control", @readonly = "readonly", placeholder = "mm/dd/yyyy hh:mm tt" })
                                    @Html.ValidationMessageFor(m => m.FromDate)
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group mar_btm10">
                                <label>To Date</label>
                                <div class="inner-addon right-addon">
                                    <i class="fa fa-calendar"></i>
                                    @Html.TextBoxFor(m => m.ToDate, "{0:MM/dd/yyyy hh:mm tt}", new { id = "ToDate", @class = "form-control", @readonly = "readonly", placeholder = "mm/dd/yyyy hh:mm tt" })
                                    @Html.ValidationMessageFor(m => m.ToDate)
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group mar_btm10">
                                <label>Account Number</label>
                                @Html.TextBoxFor(m => m.AccountNumber, new { @class = "form-control", id = "AccountNumber", placeholder = "Enter Account Number", maxlength = 7 })
                                @Html.ValidationMessageFor(m => m.AccountNumber)
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group mar_btm10">
                                <label>Type</label>
                                @Html.TextBoxFor(m => m.Type, new { @class = "form-control", id = "Type", placeholder = "Enter Type", maxlength = 15 })
                                @Html.ValidationMessageFor(m => m.Type)
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        @*<div class="col-sm-3">
                            <div class="form-group mar_btm0">
                                <label>Payment Status</label>
                                @Html.DropDownListFor(m => m.PaymentStatus, ViewBag.PaymentStatusList as SelectList, "All", new { @class = "form-control", id = "ddlStatus" })
                                @Html.ValidationMessageFor(m => m.PaymentStatus)
                            </div>
                        </div>*@
                        @*<div class="col-sm-3">
        <div class="form-group mar_btm0">
            <label>Payment Method</label>
            @Html.DropDownListFor(m => m.PaymentMethod, ViewBag.PaymentMethodList as SelectList, new { @class = "form-control", id = "ddlMethod" })
            @Html.ValidationMessageFor(m => m.PaymentMethod)
        </div
    </div>>*@
                        <div class="col-sm-4">

                        </div>
                        <div class="col-sm-2">
                            <div class="form-group text-right mar_btm0 mar_top25">
                                <input type="submit" class="btn btn-default view-report" value="View Report" />
                            </div>
                        </div>
                    </div>
                </div>

            }
            @if (ViewBag.ShowIframe)
            {
                <iframe src='@Url.Content("~/Reports/NotificationsByText.aspx")' width="100%" style="border: none;" id="report-frame"></iframe>
            }
        </div>
    </div>

</div>

@section scripts
{
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryval")
    <script src="~/Content/plugin/select2/js/select2.min.js"></script>
    <script src="~/Content/plugin/datepicker/js/jquery-datetimepicker.js"></script>
    <script>
        $.validator.defaults.focusInvalid = false;
        $.validator.unobtrusive.adapters.add(
        'isdateafter', ['propertytested', 'allowequaldates'], function (options) {
            options.rules['isdateafter'] = options.params;
            options.messages['isdateafter'] = options.message;
        });
        $.validator.addMethod("isdateafter", function (value, element, params) {
            var startdatevalue = $('input[name="' + params.propertytested + '"]').val();
            if (!value || !startdatevalue) return true;
            return (params.allowequaldates) ? Date.parse(startdatevalue) <= Date.parse(value) : Date.parse(startdatevalue) < Date.parse(value);
        }, '');
        $(function () {
            $('#FromDate').datetimepicker({
                //defaultTime: '00:01 AM',
                maxDate: new Date,
                formatTime: 'g:i A',
                format: 'm/d/Y h:i A',
                step: 5
            });
            $('#ToDate').datetimepicker({
                //defaultTime: '11:59 PM',
                maxDate: new Date,
                formatTime: 'g:i A',
                format: 'm/d/Y h:i A',
                step: 5
            });
            $('#ddlStatus').select2();
        });
    </script>
}

sp_report/SPReport_mvc/MAF.WEB/Views/Report/Test.cshtml
@model MAF.BAL.Model.UserLoginReportViewModel
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/plugin/datepicker/css/jquery-datetimepicker.css" rel="stylesheet" />
<div class="container-fluid dash_link pad_lt0 pad_rt0">
    <div class="row mar_btm10">
        <div class="col-lg-12 mobile_marbtm10">
            <h5 class="mar_top0">
                <b>User Login Report</b>
            </h5>
            @using (Html.BeginForm("Test", "Report", FormMethod.Post, new { id = "filterform" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="filter_wrapper">
                    <div class="row">
                       
                       
                        <div class="col-sm-3">
                            <div class="form-group text-right mar_btm0 mar_top25">
                                <input type="submit" class="btn btn-default view-report" value="View Report" />
                            </div>
                        </div>
                    </div>
                </div>

            }
            @if (ViewBag.ShowIframe)
            {
                <iframe src='@Url.Content("~/Reports/Test.aspx")' width="100%" style="border: none;" id="report-frame"></iframe>
            }
        </div>
    </div>

</div>

@section scripts
{
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryval")
    <script src="~/Content/plugin/select2/js/select2.min.js"></script>
   
    
}